version: "2"
# service
services:
  # web
  web:
    build: ./config/web
    ports:
      - "8080:80"
    volumes:
            - ./html/app:/var/www/html:rw
    command: /bin/sh -c "chgrp -R www-data /var/www/html && chmod g+s /var/www/html && apache2-foreground"
    restart: always
